---
- name: Configurar rutas estáticas en las máquinas virtuales
  hosts: all
  become: yes
  tasks:
    - name: Verificar e instalar Docker si es necesario
      raw: |
        if ! command -v docker > /dev/null 2>&1; then
          if command -v apt-get > /dev/null 2>&1; then
            apt-get update && apt-get install -y docker.io
          elif command -v yum > /dev/null 2>&1; then
            yum install -y docker
          elif command -v dnf > /dev/null 2>&1; then
            dnf install -y docker
          elif command -v zypper > /dev/null 2>&1; then
            zypper install -y docker
          fi
          systemctl start docker
          systemctl enable docker
        fi
      changed_when: false

    - name: Ejecutar un contenedor de Python para agregar rutas
      command: >
        docker run --rm --network host -v /etc:/etc -v /usr/sbin:/usr/sbin -v /bin:/bin -v /sbin:/sbin -v /usr/bin:/usr/bin -v /lib:/lib python:3.9 bash -c "
        if ! ip route show | grep -q '192.168.0.0/24'; then
          ip route add 192.168.0.0/24 via {{ gateway }};
        fi"
      environment:
        gateway: "{{ '10.17.3.1' if inventory_hostname in groups['kube_network_02'] else '10.17.4.1' }}"
      ignore_errors: yes