---
- name: Instalar Python en las máquinas virtuales
  hosts: all
  become: yes
  tasks:
    - name: Copiar script de instalación a las máquinas
      ansible.builtin.copy:
        src: /etc/ansible/ansible-network-setup-cluster-openshift/install_python.sh
        dest: /tmp/install_python.sh
        mode: "0755"

    - name: Ejecutar script de instalación en las máquinas
      ansible.builtin.shell: /tmp/install_python.sh
